# Generated by Django 5.2.17 on 2026-09-23 00:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField()),
                ('uncertainty', models.TextField()),
                ('location_name', models.CharField(max_length=120)),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('status', models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('corroborated', 'Corroborated'), ('confirmed', 'Confirmed by a source')], default='unconfirmed', max_length=16)),
                ('confirmation_source', models.CharField(blank=True, max_length=120)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('is_demo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'amara_incident',
                'ordering': ['-updated_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['unconfirmed', 'corroborated', 'confirmed'])), name='amara_incident_valid_status'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'confirmed'), _negated=True), models.Q(('confirmation_source', ''), _negated=True), _connector='OR'), name='amara_confirmation_attribution'), models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__gte', -90), ('latitude__isnull', False), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__isnull', False), ('longitude__lte', 180)), _connector='OR'), name='amara_incident_location_bounds')],
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('visitor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('follow_market_road', models.BooleanField(default=True)),
                ('muted', models.BooleanField(default=False)),
                ('travel_mode', models.CharField(choices=[('walking', 'Walking'), ('driving', 'Driving')], default='driving', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'amara_preference',
                'constraints': [models.CheckConstraint(condition=models.Q(('travel_mode__in', ['walking', 'driving'])), name='amara_preference_valid_mode')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('source_name', models.CharField(max_length=120)),
                ('original_text', models.TextField()),
                ('relationship', models.CharField(max_length=180)),
                ('source_url', models.URLField(blank=True)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('is_demo', models.BooleanField(default=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='amara_reports.incident')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reposts', to='amara_reports.report')),
            ],
            options={
                'db_table': 'amara_report',
                'ordering': ['published_at', 'code'],
            },
        ),
    ]
