# Generated by Django 5.2.17 on 2026-09-23 21:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amara_reports', '0002_server_only_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='queued', max_length=16)),
                ('progress', models.CharField(default='Waiting to process', max_length=160)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('claim_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('input_digest', models.CharField(blank=True, db_index=True, max_length=64)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amara_evidence_job',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=180)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'amara_incident_update',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UpdateReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('context', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'amara_update_receipt',
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='area_scope',
            field=models.CharField(default='yaba', max_length=40),
        ),
        migrations.AddField(
            model_name='incident',
            name='case_owner',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='condition',
            field=models.CharField(default='reported', max_length=24),
        ),
        migrations.AddField(
            model_name='incident',
            name='evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='incident',
            name='evidence_signature',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='incident',
            name='template_slug',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='preference',
            name='active_demo_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_visitors', to='amara_reports.incident'),
        ),
        migrations.AddField(
            model_name='preference',
            name='follow_yaba_area',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='assessment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='content_kind',
            field=models.CharField(default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='report',
            name='ingested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='retrieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='source_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('fingerprint', ''), _negated=True), fields=('incident', 'fingerprint'), name='amara_report_fingerprint_unique'),
        ),
        migrations.AddField(
            model_name='evidencejob',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='amara_reports.incident'),
        ),
        migrations.AddField(
            model_name='incidentupdate',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='amara_reports.incident'),
        ),
        migrations.AddField(
            model_name='updatereceipt',
            name='update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='amara_reports.incidentupdate'),
        ),
        migrations.AddConstraint(
            model_name='evidencejob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('incident',), name='amara_one_active_incident_job'),
        ),
        migrations.AddConstraint(
            model_name='incidentupdate',
            constraint=models.UniqueConstraint(fields=('incident', 'revision'), name='amara_incident_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='updatereceipt',
            constraint=models.UniqueConstraint(fields=('visitor_id', 'update'), name='amara_update_receipt_unique'),
        ),
    ]
