# Generated by Django 5.2.17 on 2026-09-24 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amara_reports', '0004_evidence_row_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparedDemo',
            fields=[
                ('key', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('prepared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'amara_prepared_demo',
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='amara_one_active_demo_pack')],
            },
        ),
    ]
